name = "{{project_name}}"
version = "0.1.0"
description = "An HTTP server Theater actor"
component_path = "target/wasm32-unknown-unknown/release/{{project_name_snake}}.wasm"

[interface]
implements = "theater:simple/actor"
requires = []

[[handlers]]
type = "runtime"
config = {}

[[handlers]]
type = "http-framework"
config = {}

