name = "supervisor"
version = "0.1.0"
package = "target/wasm32-unknown-unknown/release/supervisor_actor.wasm"

[[handler]]
type = "runtime"

# Spawn + supervise child actors.
[[handler]]
type = "supervisor"
