//! A `#[derive(State)]` actor that implements the **message-server-client**
//! callback interface — the client-interface CI guard.
//!
//! Nothing in CI previously spawned a real `#[derive(State)]` actor that exports
//! a client interface, so a whole class of staleness shipped unseen: the
//! state-slot pact bug (#196), the dual-`__pack_alloc` link bug (#198), and stale
//! manifest `[[handler]]` types (#199). This actor exercises the whole path — the
//! `State` derive + `get-state`, in-module mutation from a client callback, the
//! `self` + `message-server-host` imports, and the **no-state (bare-ok)**
//! `message-server-client` return convention — so a companion integration test
//! can round-trip a routed request through the message-server handler.
//!
//! - `init`: seed state, `register()` with the message router
//! - `handle-send`: count a one-way message
//! - `handle-request`: count it and reply `"response:" + <request bytes>` (bare ok)

#![no_std]

extern crate alloc;

use alloc::boxed::Box;
use alloc::string::String;
use alloc::vec;
use alloc::vec::Vec;
use packr_guest::{export, import, pack_types, GraphValue, Value, ValueType};
use theater_guest::State;

packr_guest::setup_guest!();

pack_types! {
    imports {
        theater:simple/self {
            log: func(msg: string),
        }
        theater:simple/message-server-host {
            register: func() -> result<_, string>,
        }
    }
    exports {
        theater:simple/actor.init: func(config: value) -> result<_, string>,
        // Auto-generated by #[derive(State)]; declared so `has_export` finds it.
        theater:simple/actor.get-state: func() -> value,
        // message-server-client — no-state (bare-ok) convention: own args only,
        // and the ok branch carries only the callback's own payload.
        theater:simple/message-server-client.handle-send: func(message: list<u8>) -> result<_, string>,
        theater:simple/message-server-client.handle-request: func(request-id: string, message: list<u8>) -> result<option<list<u8>>, string>,
    }
}

#[import(module = "theater:simple/self", name = "log")]
fn log(msg: String);

#[import(module = "theater:simple/message-server-host", name = "register")]
fn register() -> Result<(), String>;

/// The actor's state — request/send counters, held inside the module.
#[derive(Clone, GraphValue, State)]
struct ActorState {
    requests: i32,
    sends: i32,
}

fn ok_result(value: Value) -> Value {
    Value::Result {
        ok_type: value.infer_type(),
        err_type: ValueType::String,
        value: Ok(Box::new(value)),
    }
}

/// `result<_, string>::ok(())` — success with no payload.
fn ok_unit() -> Value {
    let unit = Value::Tuple(vec![]);
    Value::Result {
        ok_type: unit.infer_type(),
        err_type: ValueType::String,
        value: Ok(Box::new(unit)),
    }
}

fn bytes_to_list(bytes: Vec<u8>) -> Value {
    Value::List {
        elem_type: ValueType::U8,
        items: bytes.into_iter().map(Value::U8).collect(),
    }
}

/// Initialize: seed state and join the message router so requests get delivered.
#[export(name = "theater:simple/actor.init")]
fn init(_config: Value) -> Value {
    log(String::from("state-client-test: init"));
    ActorState::set(ActorState {
        requests: 0,
        sends: 0,
    });
    if let Err(e) = register() {
        log(alloc::format!("state-client-test: register failed: {}", e));
    }
    ok_unit()
}

/// Handle a one-way message — count it.
#[export(name = "theater:simple/message-server-client.handle-send")]
fn handle_send(_message: Vec<u8>) -> Value {
    let n = ActorState::with_mut(|s| {
        s.sends += 1;
        s.sends
    });
    log(alloc::format!("state-client-test: handle-send #{}", n));
    ok_unit()
}

/// Handle a request — count it and reply `"response:" + request bytes`.
/// Bare-ok: the ok branch is `option<list<u8>>` directly (no state slot).
#[export(name = "theater:simple/message-server-client.handle-request")]
fn handle_request(_request_id: String, message: Vec<u8>) -> Value {
    let n = ActorState::with_mut(|s| {
        s.requests += 1;
        s.requests
    });
    log(alloc::format!("state-client-test: handle-request #{}", n));

    let mut response = Vec::from(b"response:" as &[u8]);
    response.extend_from_slice(&message);

    let response_option = Value::Option {
        inner_type: ValueType::List(Box::new(ValueType::U8)),
        value: Some(Box::new(bytes_to_list(response))),
    };
    ok_result(response_option)
}
