//! Monitor test actor — exercises `theater:simple/lifecycle` end-to-end.
//!
//! On init it is given a subject actor id (in its init config) and calls
//! `monitor(subject)`. It exports `handle-lifecycle-event`, and records the
//! event-type of each delivered event into its in-module state, so a test can
//! spawn this actor, stop the subject, and observe (via `get-state`) that
//! `"terminated"` was delivered.
//!
//! State lives inside the module now (`docs/in-module-state.md`): the actor
//! keeps it in a `#[derive(State)]` cell, so the last event stays inspectable.

#![no_std]

extern crate alloc;

use alloc::boxed::Box;
use alloc::format;
use alloc::string::String;
use alloc::vec;
use alloc::vec::Vec;
use packr_guest::{export, import, pack_types, GraphValue, Value, ValueType};
use theater_guest::State;

packr_guest::setup_guest!();

pack_types! {
    imports {
        theater:simple/self {
            log: func(msg: string),
        }
        theater:simple/lifecycle {
            monitor: func(subject: string) -> result<_, string>,
        }
    }
    exports {
        theater:simple/actor.init: func(config: value) -> result<_, string>,
        // Auto-generated by #[derive(State)]; declared here so `has_export` finds it.
        theater:simple/actor.get-state: func() -> value,
        theater:simple/lifecycle-handlers.handle-lifecycle-event: func(subject: string, event-type: string, data: list<u8>) -> result<_, string>,
    }
}

#[import(module = "theater:simple/self", name = "log")]
fn log(msg: String);

#[import(module = "theater:simple/lifecycle", name = "monitor")]
fn monitor(subject: String) -> Result<(), String>;

/// The actor's state: the event-type of the last lifecycle event received.
#[derive(Clone, GraphValue, State)]
struct MonitorState {
    received: String,
}

/// `result<_, string>::ok(())` — nothing to return but success.
fn ok_unit() -> Value {
    let unit = Value::Tuple(vec![]);
    Value::Result {
        ok_type: unit.infer_type(),
        err_type: ValueType::String,
        value: Ok(Box::new(unit)),
    }
}

/// Pull the subject id (a utf-8 string in `option<list<u8>>`) out of init config.
fn subject_from_config(config: &Value) -> Option<String> {
    match config {
        Value::Option {
            value: Some(inner), ..
        } => match inner.as_ref() {
            Value::List { items, .. } => {
                let bytes: Vec<u8> = items
                    .iter()
                    .filter_map(|v| if let Value::U8(b) = v { Some(*b) } else { None })
                    .collect();
                String::from_utf8(bytes).ok()
            }
            _ => None,
        },
        _ => None,
    }
}

#[export(name = "theater:simple/actor.init")]
fn init(config: Value) -> Value {
    // The subject id arrives as the manifest config; unwrap any tuple wrapping.
    let config = match config {
        Value::Tuple(mut items) if !items.is_empty() => items.remove(0),
        other => other,
    };
    match subject_from_config(&config) {
        Some(subject) => {
            log(format!("monitor-test: monitoring {}", subject));
            let _ = monitor(subject);
            MonitorState::set(MonitorState {
                received: String::from("init"),
            });
        }
        None => {
            log(String::from("monitor-test: no subject id in config"));
            MonitorState::set(MonitorState {
                received: String::from("no-subject"),
            });
        }
    }
    ok_unit()
}

#[export(name = "theater:simple/lifecycle-handlers.handle-lifecycle-event")]
fn handle_lifecycle_event(input: Value) -> Value {
    // The host passes Tuple[subject, event-type, data] (no threaded state).
    let event_type = match &input {
        Value::Tuple(items) if items.len() >= 2 => match &items[1] {
            Value::String(s) => s.clone(),
            _ => String::from("?"),
        },
        _ => String::from("?"),
    };
    log(format!("monitor-test: received lifecycle event {}", event_type));
    // Record the event-type we just saw.
    MonitorState::with_mut(|s| s.received = event_type);
    ok_unit()
}
