name = "chat"
version = "0.1.0"
description = "chat actor for LLM chat application"
component_path = "/Users/colinrozzi/work/theater/examples/sample-http/target/wasm32-unknown-unknown/release/sample_http.wasm"

[interface]
implements = "ntwk:theater/single-actor"
requires = []

[[handlers]]
type = "runtime"
config = {}

[[handlers]]
type = "http-framework"
config = {}
