//! `counter` — in-module state + inter-actor messaging via `theater:simple/message-server`.
//!
//! The actor keeps a running count **inside the module** and bumps it every time
//! it receives a message. It shows the two patterns this repo now standardizes on:
//!
//! - **In-module state** (`docs/in-module-state.md`): `#[derive(State)]` gives the
//!   `Counter` a managed cell — `init` calls `Counter::set` once, `handle-send`
//!   mutates it in place with `Counter::with_mut`. Nothing is threaded through the
//!   call. The derive also emits the `theater:simple/actor.get-state` export (which
//!   we declare in `pack_types!` so the runtime's `has_export` can find it), so the
//!   count stays inspectable via `get-actor-state`.
//! - **Message-server**: `register()` (from `init`) subscribes the actor to its
//!   mailbox; `handle-send` fires for each one-way message.

#![no_std]
extern crate alloc;

use alloc::boxed::Box;
use alloc::format;
use alloc::string::String;
use alloc::vec::Vec;
use packr_guest::{export, import, pack_types, GraphValue, Value, ValueType};
use theater_guest::State;

packr_guest::setup_guest!();

pack_types! {
    imports {
        theater:simple/self {
            log: func(msg: string),
        }
        theater:simple/message-server-host {
            register: func() -> result<_, string>,
        }
    }
    exports {
        theater:simple/actor.init: func(config: value) -> result<_, string>,
        // Auto-generated by #[derive(State)]; declared here so `has_export` finds it.
        theater:simple/actor.get-state: func() -> value,
        theater:simple/message-server-client.handle-send: func(params: value) -> result<_, string>,
    }
}

#[import(module = "theater:simple/self", name = "log")]
fn log(msg: String);

#[import(module = "theater:simple/message-server-host", name = "register")]
fn register() -> Result<(), String>;

/// The actor's state: a running count, held inside the module.
#[derive(Clone, GraphValue, State)]
struct Counter {
    count: u64,
}

/// `result<_, string>::ok(())` — nothing to return but success.
fn ok_unit() -> Value {
    let unit = Value::Tuple(Vec::new());
    Value::Result {
        ok_type: unit.infer_type(),
        err_type: ValueType::String,
        value: Ok(Box::new(unit)),
    }
}

#[export(name = "theater:simple/actor.init")]
fn init(_config: Value) -> Value {
    // Subscribe to our mailbox so `handle-send` starts firing.
    let _ = register();
    Counter::set(Counter { count: 0 });
    log(String::from("counter: initialized at 0"));
    ok_unit()
}

#[export(name = "theater:simple/message-server-client.handle-send")]
fn handle_send(_params: Value) -> Value {
    let next = Counter::with_mut(|c| {
        c.count += 1;
        c.count
    });
    log(format!("counter: bumped to {}", next));
    ok_unit()
}
