[package]
name = "state-test-actor"
version = "0.1.0"
edition = "2021"

[workspace]

[lib]
crate-type = ["cdylib"]

[dependencies]
packr-guest = { version = "0.23.0", features = ["derive"] }
packr-abi = { version = "0.23.0", default-features = false }
theater-guest = { path = "../../crates/theater-guest" }

[profile.release]
opt-level = "s"
lto = true
