name = "{{project_name}}"
version = "0.1.0"
description = "A basic Theater actor"
component_path = "not yet build"
save_chain = true

[interface]
implements = "theater:simple/actor"
requires = []

[[handlers]]
type = "runtime"
config = {}

