//! Supervisor replay test actor for Pack runtime.
//!
//! A deterministic actor that exercises supervisor host functions:
//! - Imports `theater:simple/self.log`
//! - Imports `theater:simple/supervisor.{spawn, list-actors, stop-actor}`
//! - Exports `theater:simple/actor.init`
//! - Exports `theater:simple/message-server-client.handle-send`
//! - Exports `theater:simple/supervisor-handlers.handle-lifecycle-event`
//!
//! Commands (sent as message bytes in handle-send):
//! - `"spawn:<manifest_path>"` → spawn a child, store child_id in state
//! - `"list"` → list actors in view, log the count
//! - `"stop"` → read child_id from state, stop it
//!
//! State lives inside the module now (`docs/in-module-state.md`): the spawned
//! child's id is held in a `#[derive(State)]` cell (inspectable via `get-state`).

#![no_std]

extern crate alloc;

use alloc::boxed::Box;
use alloc::format;
use alloc::string::String;
use alloc::vec;
use alloc::vec::Vec;
use packr_guest::{export, import, pack_types, GraphValue, Value, ValueType};
use theater_guest::State;

packr_guest::setup_guest!();

// Embed interface metadata for hash verification. The supervisor types below
// mirror theater:simple/supervisor exactly (field/case names + order) so the
// host's interface subset hash matches — get this wrong and the actor compiles
// but fails to instantiate.
pack_types! {
    record actor-info {
        id: string,
        name: string,
        parent-id: option<string>,
    }

    variant spawn-failure {
        bad-manifest(string),
        wasm-fetch(string),
        handler-registry(string),
        wasm-invalid(string),
        interface-mismatch(string),
        missing-interface(string),
        missing-metadata(string),
        init-failed(string),
        child-failed(string),
        child-stopped(string),
        timeout(string),
        internal(string),
    }

    variant supervisor-error {
        actor-not-found(string),
        out-of-view(string),
        permission-denied(string),
        invalid-argument(string),
        spawn-failed(spawn-failure),
        runtime-unavailable,
        internal(string),
    }

    imports {
        theater:simple/self {
            log: func(msg: string),
        }
        theater:simple/supervisor {
            spawn: func(manifest: string, init-state: option<value>, wasm-bytes: option<list<u8>>) -> result<string, supervisor-error>,
            list-actors: func() -> result<list<actor-info>, supervisor-error>,
            stop-actor: func(id: string) -> result<_, supervisor-error>,
        }
        theater:simple/message-server-host {
            register: func() -> result<_, string>,
        }
    }
    exports {
        theater:simple/actor.init: func(config: value) -> result<_, string>,
        // Auto-generated by #[derive(State)]; declared here so `has_export` finds it.
        theater:simple/actor.get-state: func() -> value,
        theater:simple/message-server-client.handle-send: func(params: value) -> result<_, string>,
        theater:simple/supervisor-handlers.handle-lifecycle-event: func(id: string, event-type: string, data: list<u8>) -> result<_, string>,
    }
}

// ============================================================================
// Host imports
// ============================================================================

#[import(module = "theater:simple/self", name = "log")]
fn log(msg: String);

// The supervisor ops return `result<T, supervisor-error>`; import them raw and
// parse the Value so the actor can react to the structured error case.
#[import(module = "theater:simple/supervisor", name = "spawn")]
fn supervisor_spawn_raw(
    manifest_path: String,
    init_state: Option<Value>,
    wasm_bytes: Option<Vec<u8>>,
) -> Value;

#[import(module = "theater:simple/supervisor", name = "list-actors")]
fn supervisor_list_actors_raw() -> Value;

#[import(module = "theater:simple/supervisor", name = "stop-actor")]
fn supervisor_stop_actor_raw(id: String) -> Value;

/// Render a `supervisor-error` variant Value as its case name.
fn supervisor_error_case(v: Option<Value>) -> String {
    match v {
        Some(Value::Variant { case_name, .. }) => case_name,
        _ => String::from("unknown"),
    }
}

/// spawn -> Ok(child-id) | Err(case-name)
fn supervisor_spawn(manifest_path: String) -> Result<String, String> {
    match supervisor_spawn_raw(manifest_path, None, None) {
        Value::Variant { tag: 0, payload, .. } => match payload.into_iter().next() {
            Some(Value::String(id)) => Ok(id),
            _ => Err(String::from("unexpected ok payload")),
        },
        Value::Variant { tag: 1, payload, .. } => {
            Err(supervisor_error_case(payload.into_iter().next()))
        }
        _ => Err(String::from("unexpected result format")),
    }
}

/// list-actors -> Ok(count) | Err(case-name)
fn supervisor_list_actors_count() -> Result<usize, String> {
    match supervisor_list_actors_raw() {
        Value::Variant { tag: 0, payload, .. } => match payload.into_iter().next() {
            Some(Value::List { items, .. }) => Ok(items.len()),
            _ => Err(String::from("unexpected ok payload")),
        },
        Value::Variant { tag: 1, payload, .. } => {
            Err(supervisor_error_case(payload.into_iter().next()))
        }
        _ => Err(String::from("unexpected result format")),
    }
}

/// stop-actor -> Ok(()) | Err(case-name)
fn supervisor_stop_actor(id: String) -> Result<(), String> {
    match supervisor_stop_actor_raw(id) {
        Value::Variant { tag: 0, .. } => Ok(()),
        Value::Variant { tag: 1, payload, .. } => {
            Err(supervisor_error_case(payload.into_iter().next()))
        }
        _ => Err(String::from("unexpected result format")),
    }
}

#[import(module = "theater:simple/message-server-host", name = "register")]
fn message_server_register() -> Result<(), String>;

// ============================================================================
// State
// ============================================================================

/// The actor's state: the id of the child it spawned (if any).
#[derive(Clone, GraphValue, State)]
struct SupState {
    child_id: Option<String>,
}

// ============================================================================
// Actor exports
// ============================================================================

#[export(name = "theater:simple/actor.init")]
fn init(_config: Value) -> Value {
    log(String::from("supervisor-replay-test: init called"));

    SupState::set(SupState { child_id: None });

    // Register with message server to receive commands
    if let Err(e) = message_server_register() {
        log(format!("supervisor-replay-test: register failed: {}", e));
        return err_result("Failed to register with message server");
    }
    log(String::from("supervisor-replay-test: registered with message server"));

    log(String::from("supervisor-replay-test: init complete"));

    ok_unit()
}

#[export(name = "theater:simple/message-server-client.handle-send")]
fn handle_send(input: Value) -> Value {
    // The host passes params `tuple<list<u8>>`; value-mode unwraps the 1-tuple
    // to the message bytes. Accept either shape defensively.
    let msg_bytes = match input {
        Value::List { .. } => extract_bytes(input),
        Value::Tuple(mut items) if !items.is_empty() => extract_bytes(items.remove(items.len() - 1)),
        _ => vec![],
    };
    let msg = match core::str::from_utf8(&msg_bytes) {
        Ok(s) => s,
        Err(_) => {
            log(String::from("supervisor-replay-test: handle-send received non-utf8 data"));
            return ok_unit();
        }
    };

    log(format!("supervisor-replay-test: handle-send: {}", msg));

    if let Some(manifest_path) = msg.strip_prefix("spawn:") {
        log(format!(
            "supervisor-replay-test: spawning child from {}",
            manifest_path
        ));
        match supervisor_spawn(String::from(manifest_path)) {
            Ok(child_id) => {
                log(format!("supervisor-replay-test: spawned child {}", child_id));
                SupState::with_mut(|s| s.child_id = Some(child_id));
            }
            Err(e) => {
                log(format!("supervisor-replay-test: spawn error: {}", e));
            }
        }
        return ok_unit();
    } else if msg == "list" {
        log(String::from("supervisor-replay-test: listing actors in view"));
        match supervisor_list_actors_count() {
            Ok(n) => log(format!("supervisor-replay-test: actor count: {}", n)),
            Err(e) => log(format!("supervisor-replay-test: list error: {}", e)),
        }
        return ok_unit();
    } else if msg == "stop" {
        match SupState::with(|s| s.child_id.clone()) {
            Some(child_id) => {
                log(format!("supervisor-replay-test: stopping child {}", child_id));
                match supervisor_stop_actor(child_id) {
                    Ok(()) => {
                        log(String::from("supervisor-replay-test: stop-actor succeeded"));
                    }
                    Err(e) => {
                        log(format!("supervisor-replay-test: stop error: {}", e));
                    }
                }
            }
            None => {
                log(String::from("supervisor-replay-test: no child_id in state"));
            }
        }
        return ok_unit();
    }

    log(String::from("supervisor-replay-test: unknown command"));
    ok_unit()
}

#[export(name = "theater:simple/supervisor-handlers.handle-lifecycle-event")]
fn handle_lifecycle_event(input: Value) -> Value {
    // The host passes Tuple[id, event-type, data] (no threaded state).
    let id = match &input {
        Value::Tuple(items) if !items.is_empty() => match &items[0] {
            Value::String(s) => s.clone(),
            _ => String::from("unknown"),
        },
        _ => String::from("unknown"),
    };

    log(format!("supervisor-replay-test: child terminated: {}", id));

    ok_unit()
}

// ============================================================================
// Helpers
// ============================================================================

/// Extract bytes from a Value::List of U8
fn extract_bytes(value: Value) -> Vec<u8> {
    match value {
        Value::List { items, .. } => items
            .into_iter()
            .filter_map(|v| match v {
                Value::U8(b) => Some(b),
                _ => None,
            })
            .collect(),
        _ => Vec::new(),
    }
}

/// Return an error result
fn err_result(msg: &str) -> Value {
    Value::Result {
        ok_type: ValueType::Tuple(vec![]),
        err_type: ValueType::String,
        value: Err(Box::new(Value::String(String::from(msg)))),
    }
}

/// `result<_, string>::ok(())` — no state to return.
fn ok_unit() -> Value {
    let unit = Value::Tuple(vec![]);
    Value::Result {
        ok_type: unit.infer_type(),
        err_type: ValueType::String,
        value: Ok(Box::new(unit)),
    }
}
