package ntwk:theater;

interface message-server-client {
    use types.{json, event};

    handle-send: func(state: option<json>, params: tuple<json>) -> tuple<option<json>>;
    handle-request: func(state: option<json>, params: tuple<json>) -> tuple<option<json>, tuple<json>>;
}

interface message-server-host {
    use types.{json, actor-id};

    // send and forget message
    send: func(actor-id: actor-id, msg: json) -> result<_, string>;

    // send message and wait for response
    request: func(actor-id: actor-id, msg: json) -> result<json, string>;
}
