[template]
name = "supervisor"
description = "A Theater actor with supervisor capabilities for managing child actors"

[files]
"Cargo.toml" = "Cargo.toml"
"manifest.toml" = "manifest.toml"
"wit/world.wit" = "world.wit"
"src/lib.rs" = "lib.rs"
"README.md" = "README.md"
"wkg.toml" = "wkg.toml"
".gitignore" = ".gitignore"
