name = "environment-example"
version = "0.1.0"
description = "A basic Theater actor with environment access"
component_path = "not_yet_built.wasm"
save_chain = true

[interface]
implements = "ntwk:theater/actor"
requires = []

[[handlers]]
type = "runtime"
config = {}

[[handlers]]
type = "environment"
config = { 
    allowed_prefixes = ["APP_", "PUBLIC_"],
    denied_vars = ["PATH", "HOME", "USER", "PWD"],
    allow_list_all = false 
}
