# Theater Actor Manifest Template
name = "example-actor"
component_path = "example.wasm"

[interface]
implements = "ntwk:simple-actor/actor"
requires = []

# Optional message-server capability
[[handlers]]
type = "message-server"
config = { port = 8080 }
interface = "ntwk:theater/message-server-client"

# Optional HTTP server capability
[[handlers]]
type = "http-server" 
config = { port = 8081 }

# Optional supervisor capability for managing child actors
# [[handlers]]
# type = "supervisor"
# config = {}
