use anyhow::Result;
use theater::actor_handle::ActorHandle;
use theater::actor_runtime::ActorRuntime;
use theater::chain::StateChain;
use theater::config::ManifestConfig;
use theater::events::{ChainEventData, EventData};
use theater::id::TheaterId;
use theater::messages::TheaterCommand;
use std::time::{Duration, SystemTime, UNIX_EPOCH};
use tokio::sync::mpsc;