package test:wasi-clocks;

world wasi-clocks-test {
    import wasi:clocks/wall-clock@0.2.3;
    import wasi:clocks/monotonic-clock@0.2.3;
    import wasi:io/poll@0.2.3;
    export theater:simple/actor;
}
