# HTTP Server Actor Template
name = "http-server-actor"
component_path = "http-server.wasm"

[interface]
implements = "ntwk:server-actor/server-actor"
requires = []

# HTTP server capability
[[handlers]]
type = "http-server"
config = { port = 8080 }

[logging]
level = "info"
chain_events = true
