# Supervisor Actor Template
name = "supervisor-actor"
component_path = "supervisor.wasm"

[interface]
implements = "ntwk:supervisor-actor/supervisor-actor"
requires = []

# Supervisor capability
[[handlers]]
type = "supervisor"
config = {}

# Optional HTTP server for management
[[handlers]]
type = "http-server"
config = { port = 8081 }

[logging]
level = "info"
chain_events = true
