//! A simple state tracking test actor.
//!
//! State lives inside the module now (`docs/in-module-state.md`): the actor
//! keeps its count in a `#[derive(State)]` cell, sets it in `init`, and mutates
//! it in place from each export. Nothing is threaded through the call.
//!
//! - `init`: seeds the count to 0
//! - `increment`: bumps the count, returns the new count
//! - `get-count`: returns the current count without modifying it
//! - `get-state`: auto-generated by `#[derive(State)]`, keeps the actor inspectable

#![no_std]

extern crate alloc;

use alloc::boxed::Box;
use alloc::format;
use alloc::string::String;
use alloc::vec;
use packr_guest::{export, import, pack_types, GraphValue, Value, ValueType};
use theater_guest::State;

// Set up allocator and panic handler
packr_guest::setup_guest!();

// Embed interface metadata
pack_types! {
    imports {
        theater:simple/self {
            log: func(msg: string),
        }
    }
    exports {
        theater:simple/actor.init: func(config: value) -> result<_, string>,
        // Auto-generated by #[derive(State)]; declared here so `has_export` finds it.
        theater:simple/actor.get-state: func() -> value,
        theater:simple/state-test.increment: func() -> result<s32, string>,
        theater:simple/state-test.get-count: func() -> result<s32, string>,
    }
}

// Import the log function from the host
#[import(module = "theater:simple/self", name = "log")]
fn log(msg: String);

/// The actor's state: a running count, held inside the module.
#[derive(Clone, GraphValue, State)]
struct ActorState {
    count: i32,
}

fn ok_result(value: Value) -> Value {
    Value::Result {
        ok_type: value.infer_type(),
        err_type: ValueType::String,
        value: Ok(Box::new(value)),
    }
}

/// `result<_, string>::ok(())` — nothing to return but success.
fn ok_unit() -> Value {
    let unit = Value::Tuple(vec![]);
    Value::Result {
        ok_type: unit.infer_type(),
        err_type: ValueType::String,
        value: Ok(Box::new(unit)),
    }
}

/// Initialize the actor — seed the count to 0.
#[export(name = "theater:simple/actor.init")]
fn init(_config: Value) -> Value {
    log(String::from("state-test: init called"));
    ActorState::set(ActorState { count: 0 });
    log(format!("state-test: initialized with count = 0"));
    ok_unit()
}

/// Increment the counter and return the new count.
#[export(name = "theater:simple/state-test.increment")]
fn increment() -> Value {
    let new_count = ActorState::with_mut(|s| {
        s.count += 1;
        s.count
    });
    log(format!("state-test: count incremented to {}", new_count));
    ok_result(Value::S32(new_count))
}

/// Get the current count without modifying state.
#[export(name = "theater:simple/state-test.get-count")]
fn get_count() -> Value {
    let count = ActorState::with(|s| s.count);
    log(format!("state-test: current count = {}", count));
    ok_result(Value::S32(count))
}
