//! Environment handler event types
//!
//! This module defines all event types generated by the Environment handler.
//! Applications using this handler must implement `From<EnvironmentEventData>` for
//! their event type to enable type-safe event recording.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

/// Events generated by the Environment handler
///
/// These events track environment variable access, permission checks,
/// and handler lifecycle operations.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum EnvironmentEventData {
    /// Environment variable was accessed
    #[serde(rename = "get_var")]
    GetVar {
        variable_name: String,
        success: bool,
        value_found: bool,
        timestamp: DateTime<Utc>,
    },

    /// Permission was denied for an operation
    #[serde(rename = "permission_denied")]
    PermissionDenied {
        operation: String,
        variable_name: String,
        reason: String,
    },

    /// An error occurred during an operation
    #[serde(rename = "error")]
    Error {
        operation: String,
        message: String,
    },

    /// Handler setup began
    HandlerSetupStart,

    /// Handler setup completed successfully
    HandlerSetupSuccess,

    /// Handler setup encountered an error
    HandlerSetupError {
        error: String,
        step: String,
    },

    /// Linker instance was created successfully
    LinkerInstanceSuccess,

    /// Function setup began
    FunctionSetupStart {
        function_name: String,
    },

    /// Function setup completed successfully
    FunctionSetupSuccess {
        function_name: String,
    },
}
