[book]
authors = ["colin"]
language = "en"
multilingual = false
src = "src"
title = "Theater Docs"

[output.html]
git-repository-url = "https://github.com/colinrozzi/theater"
edit-url-template = "https://github.com/colinrozzi/theater/edit/main/book/{path}"
site-url = "/theater/guide/"
additional-css = ["css/custom.css"]

# Add a custom entry in the navigation menu linking to API docs
[output.html.navbar]
additional-items = [
    { url = "../api/theater/index.html", text = "API Reference" }
]