name: Deploy Documentation
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'
          
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      
      - name: Build Book
        working-directory: ./book
        run: mdbook build
      
      - name: Build API docs
        run: cargo doc --no-deps --all-features
      
      # Create redirect index.html
      - name: Create landing page
        run: |
          mkdir -p combined-docs
          cp -r book/book combined-docs/guide
          cp -r target/doc combined-docs/api
          cat > combined-docs/index.html << EOF
          <!DOCTYPE html>
          <html>
            <head>
              <meta charset="utf-8">
              <title>Theater Documentation</title>
              <meta http-equiv="refresh" content="0; url=guide/index.html">
              <style>
                body {
                  font-family: sans-serif;
                  max-width: 800px;
                  margin: 0 auto;
                  padding: 30px;
                }
                .container {
                  display: flex;
                  gap: 20px;
                  margin-top: 30px;
                }
                .button {
                  display: inline-block;
                  padding: 10px 20px;
                  background-color: #2b6cb0;
                  color: white;
                  text-decoration: none;
                  border-radius: 4px;
                  font-weight: bold;
                }
              </style>
            </head>
            <body>
              <h1>Theater Documentation</h1>
              <p>Redirecting to the guide...</p>
              <div class="container">
                <a class="button" href="guide/index.html">User Guide</a>
                <a class="button" href="api/theater/index.html">API Reference</a>
              </div>
            </body>
          </html>
          EOF

      - name: Deploy
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./combined-docs
          force_orphan: true