name: Deploy Documentation
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'
          
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      
      - name: Build Book
        working-directory: ./book
        run: mdbook build
      
      - name: Build API docs
        run: cargo doc --no-deps --all-features --document-private-items
      
      # Setup documentation structure without custom landing page
      - name: Setup Documentation Structure
        run: |
          mkdir -p combined-docs
          # Copy mdBook output directly to the root of combined-docs
          cp -r book/book/* combined-docs/guide
          # Create api directory and copy API docs there
          mkdir -p combined-docs/api
          cp -r target/doc/* combined-docs/api/

      - name: Deploy
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./combined-docs
          force_orphan: true
